# Generated by Django 5.1 on 2025-10-27 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanico', models.CharField(max_length=100)),
                ('tablerista', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('chasis', models.CharField(max_length=50, unique=True)),
                ('emblema', models.BooleanField(default=False)),
                ('espejos', models.BooleanField(default=False)),
                ('tapas_aros', models.BooleanField(default=False)),
                ('faros', models.BooleanField(default=False)),
                ('micas', models.BooleanField(default=False)),
                ('tp_parachoque', models.BooleanField(default=False)),
                ('bota_agua', models.BooleanField(default=False)),
                ('plumillas', models.BooleanField(default=False)),
                ('bocina', models.BooleanField(default=False)),
                ('autorradio', models.BooleanField(default=False)),
                ('pantalla', models.BooleanField(default=False)),
                ('camara_retro', models.BooleanField(default=False)),
                ('direccionales', models.BooleanField(default=False)),
                ('intermitentes', models.BooleanField(default=False)),
                ('aire_ac', models.BooleanField(default=False)),
                ('espejo_interior', models.BooleanField(default=False)),
                ('alza_vidrios', models.BooleanField(default=False)),
                ('mirror', models.BooleanField(default=False)),
                ('herramienta', models.BooleanField(default=False)),
                ('triangulo', models.BooleanField(default=False)),
                ('llave_rueda', models.BooleanField(default=False)),
                ('palanca', models.BooleanField(default=False)),
                ('gato', models.BooleanField(default=False)),
                ('inflador', models.BooleanField(default=False)),
                ('bateria', models.BooleanField(default=False)),
                ('tapa_radiador', models.BooleanField(default=False)),
                ('varilla_aceite', models.BooleanField(default=False)),
                ('tapa_liquido', models.BooleanField(default=False)),
                ('neblinero', models.BooleanField(default=False)),
                ('parabrisa', models.BooleanField(default=False)),
                ('llave_control', models.BooleanField(default=False)),
                ('pisos', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
