# Generated by Django 5.1 on 2025-10-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
